language: python
sudo: required
python:
    - '3.6'
install:
    - pip install 'numpy>=1.14'
    - pip install 'git+https://github.com/keras-team/keras@7fe2a04754e7a8d25f45a67a90e0ebd23beeed14'
    - pip install 'opencv-python>=3.3.0'
    - pip install 'pillow'
    - pip install 'tensorflow'
    - pip install 'git+https://github.com/broadinstitute/keras-resnet'
    - pip install 'pytest-flake8'
    - pip install 'cython'
    - pip install 'matplotlib'
    - pip install 'h5py'
    - pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
cache: pip
script:
    - python -m pytest tests/bin/test_train.py --flake8 -x
